# Generated by Django 5.0.6 on 2024-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='No_image_available.png', upload_to=''),
        ),
    ]
