# Generated by Django 5.0.6 on 2024-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='starting_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
